### ISSUE TITLE
[rfe] - re-use ocp-diag-pcicrawler libraries

### ISSUE THREAD

**Issue by cz172638** [awilliam/vfio-python#2]
[ocp-diag-pcicrawler](https://github.com/opencomputeproject/ocp-diag-pcicrawler) looks maintained would be good to reuse it

**Comment by awilliam** [comment]
Nak, code there seems to require root access, the nvme test driver is the only thing that walks PCI in this repo.  PCI-sysfs does not require elevated privileges for reading standard config space, which is all we need to list by class code.
