### ISSUE TITLE
[rfe] - support for non-nvme and vfio-platform devices

### ISSUE THREAD

**Issue by cz172638** [awilliam/vfio-python#3]
i'm playing with pcie endpoint on arm soc boards (rk3399, j271e, armada 3720, ...)
goal is to have userspace-to-userspace communication over pcie, using low budget devices in python.
on arm boards i would like to have module vfio-platform loaded instead of pci-endpoint driver

**Comment by awilliam** [comment]
I don't understand what you're asking for here, the base classes of container.py, group.py, and device.py are already not NVMe or PCI specific.  Use them.  Extend them for vfio-platform devices if you wish.
